<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Catching exceptions with a minimum of effort</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="(For beginners) 

 Handling exceptions is a good habit, but if you write try-except trees for all cases, these constructions start repeating, and the ...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>Catching exceptions with a minimum of effort</h1><div class="post__text post__text-html js-mediator-article">  <em>(For beginners)</em> <br><br>  Handling exceptions is a good habit, but if you write try-except trees for all cases, these constructions start repeating, and the code becomes complicated and hard to read.  And also to write all the processing of prosot laziness. <br><br>  In order for exception handling not to be painful, and to reduce the repeatability of the code, you need to use the power and flexibility of Python. <a name="habracut"></a>
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
    <h4>  Introduction </h4><br>  In general, exceptions to the program sooner or later arise even if you follow the precautions and check everything in advance. <br><br>  For example, a service script that does several actions (take from one folder, copy to another, create a third, link the file into the fourth).  You can make it smart, so that it checks everything in advance: whether there are files, whether there is access to them, etc., and if something is wrong, I told everything to the user and did nothing.  But this does not guarantee at all that the action itself will be executed: that after checking the disk will not be full, will not be disconnected, or the file will not be erased.  Sooner or later such a situation will arise, and it is better that the program be able to adequately leave it. <br><br>  Correct error message is always better than tracing.  Take a look: <br><blockquote><ol><li> <code><font color="black"><font color="#ff7700"><b>import</b></font> <font color="#dc143c">os</font> <font color="#dc143c">os</font> .listdir( <font color="#008000">dir</font> )</font></code> </li> <li> <code><font color="black"><font color="#ff7700"><b>import</b></font> <font color="#dc143c">os</font> <font color="#dc143c">os</font> .listdir( <font color="#008000">dir</font> )</font></code> </li> </ol><br></blockquote><br><br><pre> Traceback (most recent call last):
   File "/tmp/test.py", line 12, in &lt;module&gt;
	 os.listdir (dir)
 OSError: [Errno 13] Permission denied: '/ root'
</pre><br>  The user sees the incomprehensible word traceback and a bunch of unnecessary information (and if the chain is called N several functions, the trace will be N times longer). <br><br>  In principle, you can enclose the entire program in try, catch the exception, and write something: <br><blockquote><ol><li>  <font color="#ff7700"><b>import</b></font> <font color="#dc143c">os</font> , <font color="#dc143c">shutil</font> , <font color="#dc143c">sys</font> </li><li></li><li>  <font color="#ff7700"><b>try</b></font> : </li><li>  <font color="#dc143c">os</font> .listdir ( <font color="#483d8b">'/ etc'</font> ) </li><li>  <font color="#dc143c">shutil</font> .  <font color="#dc143c">copy</font> ( <font color="#483d8b">'/home/culebron/test.txt'</font> , <font color="#483d8b">'/ etc'</font> ) </li><li>  <font color="#dc143c">os</font> .listdir ( <font color="#483d8b">'/ root'</font> ) </li><li>  f = <font color="#008000">open</font> ( <font color="#483d8b">'/ etc / hosts'</font> , <font color="#483d8b">'a'</font> ) </li><li>  f.write ( <font color="#483d8b">')</font> </li><li>  <font color="#483d8b">except (OSError, IOError):</font> </li><li>  <font color="#483d8b">print '</font> Error <font color="#808080"><i># {1 [1] [0]}: {1 [1] [1]}'. format (dir, sys.exc_info ())</i></font> </li></ol><br></blockquote><br><br><pre>	 Error # 13: Permission denied
</pre><br><br>  <em>(Note for beginners: after except, it is highly desirable to specify the type of exception in order to intercept only the provided type and not suppress the rest.)</em> <br><br>  Now the message is readable, but what and where has broken is not clear, but if the message were accurate (for example, ‚ÄúIt is impossible to read the folder / root‚Äù), a competent user would understand what was the matter. <br><br>  Homework, which was mentioned above: make with the help of code trees so that it is precisely clear what action did not work and what error occurred.  For example, so (language does not matter): <br><br><pre>	 Unable to read / root folder.  Mistake number 13: Permission denied
</pre><br><br><h4>  Simplest standard handler </h4><br>  Here is a simple script, more like a useful program.  He writes a new line to the / etc / hosts file, and then displays its contents: <br><blockquote><ol><li>  <font color="#808080"><i>#! / usr / bin / python</i></font> </li><li></li><li>  myfile = <font color="#483d8b">'/ etc / hosts'</font> </li><li>  <font color="#ff7700"><b>try</b></font> : </li><li>  <font color="#ff7700"><b>with</b></font> <font color="#008000">open</font> (myfile, <font color="#483d8b">'a'</font> ) <font color="#ff7700"><b>as</b></font> f: </li><li>  f.write ( <font color="#483d8b">'127.0.0.1 anotherhost'</font> ) </li><li>  <font color="#ff7700"><b>except</b></font> ( <font color="#008000">OSError</font> , <font color="#008000">IOError</font> ): </li><li>  <font color="#dc143c">sys</font> .exit ( <font color="#483d8b">'Error when working with .format file (args [], sys.exc_info () [1] .args))</font> </li><li></li><li>  <font color="#483d8b">try:</font> </li><li>  <font color="#483d8b">with open (myfile, '</font> a <font color="#483d8b">') as f:</font> </li><li>  <font color="#483d8b">print '</font> <font color="#483d8b">' .join (f)</font> </li><li>  <font color="#483d8b">except (OSError, IOError):</font> </li><li>  <font color="#483d8b">sys.exit ('</font> Error when working with .format file (args [], <font color="#dc143c">sys</font> .exc_info () [ <font color="#ff4500">1</font> ] .args)) </li></ol><br></blockquote><br><br>  Obviously, the code is repeated, and much of it can be brought into the general method.  Let's create a module in which we will write down all the methods for automatic exception handling.  Here I give examples only for training purposes, for a console script that simply stops in case of failure. <br><br><blockquote><ol><li>  <font color="#808080"><i>#! / usr / bin / python</i></font> </li><li>  <font color="#ff7700"><b>import</b></font> <font color="#dc143c">sys</font> </li><li>  <font color="#ff7700"><b>def</b></font> fopen ( <font color="#66cc66">*</font> args): </li><li>  <font color="#ff7700"><b>try</b></font> : </li><li>  <font color="#ff7700"><b>return</b></font> <font color="#008000">open</font> ( <font color="#66cc66">*</font> args) </li><li>  <font color="#ff7700"><b>except</b></font> ( <font color="#008000">OSError</font> , <font color="#008000">IOError</font> ): </li><li>  <font color="#dc143c">sys</font> .exit ( <font color="#483d8b">'Error opening .format file (args [], sys.exc_info () [1] .args))</font> </li></ol><br></blockquote><br><br>  Save the file as safe and load it from the working script: <br><br><blockquote><ol><li>  <font color="#808080"><i>#! / usr / bin / python</i></font> </li><li>  <font color="#ff7700"><b>import</b></font> safe </li><li></li><li>  myfile = <font color="#483d8b">'/ etc / hosts'</font> </li><li>  <font color="#ff7700"><b>with</b></font> safe.fopen (myfile, <font color="#483d8b">'a'</font> ) <font color="#ff7700"><b>as</b></font> f: </li><li>  a.write ( <font color="#483d8b">'127.0.0.1 anotherhost'</font> ) </li><li></li><li>  <font color="#ff7700"><b>with</b></font> safe.fopen (myfile, <font color="#483d8b">'r'</font> ) <font color="#ff7700"><b>as</b></font> f: </li><li>  <font color="#ff7700"><b>print</b></font> <font color="#483d8b">''</font> .join (f) </li></ol><br></blockquote><br><br>  Now the script will beautifully stop if you execute it without sudo.  Of course, if the failure occurs already during the writing or reading, it will not be intercepted, but later we will make protection for such cases. <br><br><h4>  Methods for wider use </h4><br>  So, we replaced the open function with our own, but in real problems we will need to work with a dozen more functions - <br>  os.listdir, os.chmod, os.chown, shutil.copy, shutil.mv, shutil.mkdir, shutil.makedirs, and others.  They need their own and understandable error messages. <br><br>  There are 2 solutions: <br><br>  make a method that will handle exceptions and call the specified method <br>  replace methods (i.e. decorate existing ones) <br><br>  From simple to complex: first try the first method, the method that calls the given one. <br><br>  In the safe.py module, create a method <br><br><blockquote><ol><li>  <font color="#ff7700"><b>def</b></font> catch (method, args, message, <font color="#dc143c">exceptions</font> = ( <font color="#008000">OSError</font> , <font color="#008000">IOError</font> )): </li><li>  <font color="#ff7700"><b>if</b></font> <font color="#ff7700"><b>not</b></font> <font color="#008000">isinstance</font> (args, ( <font color="#008000">list</font> , <font color="#008000">tuple</font> )): </li><li>  args = [args] </li><li>  <font color="#ff7700"><b>try</b></font> : </li><li>  <font color="#ff7700"><b>return</b></font> method ( <font color="#66cc66">*</font> args) </li><li>  <font color="#ff7700"><b>except</b></font> <font color="#dc143c">exceptions</font> : </li><li>  quit (message.format ( <font color="#66cc66">*</font> args) + <font color="#483d8b">'.format (sys.exc_info () [1] .args), 1)</font> </li></ol><br></blockquote><br><br>  Now you can call any functions and handle errors, indicating only an error message in place: <br><br><blockquote><ol><li>  safe.catch ( <font color="#dc143c">os</font> .listdir, <font color="#483d8b">'/ root'</font> , <font color="#483d8b">'Unable to open {0}'</font> ) </li><li>  safe.catch ( <font color="#dc143c">shutil</font> . <font color="#dc143c">copy</font> , (pathA, pathB), <font color="#483d8b">'Cannot copy {0} to {1}'</font> ) </li></ol><br></blockquote><br><br>  This view is applicable, but less readable, because the action itself (os.listdir) is not at the beginning of the line, but in brackets. <br><br>  Let's try the second way - to replace the method, that is, to decorate.  We will need the first method, catch, we will rewrite it a little, so that we can call functions with key arguments, and create a decorator that will make a wrapper calling catch: <br><br><blockquote><ol><li>  <font color="#ff7700"><b>def</b></font> catch (method, message, <font color="#dc143c">exceptions</font> , <font color="#66cc66">*</font> args, <font color="#66cc66">**</font> kwargs): </li><li>  <font color="#ff7700"><b>if</b></font> <font color="#ff7700"><b>not</b></font> <font color="#008000">isinstance</font> (message, <font color="#008000">str</font> ): </li><li>  <font color="#ff7700"><b>raise</b></font> <font color="#008000">TypeError</font> ( <font color="#483d8b">'Message text must be a string'</font> ) </li><li>  <font color="#ff7700"><b>try</b></font> : </li><li>  <font color="#ff7700"><b>return</b></font> method ( <font color="#66cc66">*</font> args) </li><li>  <font color="#ff7700"><b>except</b></font> <font color="#dc143c">exceptions</font> : </li><li>  <font color="#dc143c">sys</font> .exit (message.format ( <font color="#66cc66">*</font> args) + <font color="#483d8b">'+'</font> , <font color="#483d8b">'.join (sys.exc_info () [1] .args), 1)</font> </li><li></li><li>  <font color="#483d8b">def wrap (method, message, exceptions = (IOError, OSError)):</font> </li><li>  <font color="#483d8b">def fn (* args, ** kwargs):</font> </li><li>  <font color="#483d8b">return catch (method, message, exceptions, * args, ** kwargs)</font> </li><li>  <font color="#483d8b">return fn</font> </li><li></li><li>  <font color="#483d8b">open = wrap (open, '</font> Can) </li></ol><br></blockquote><br><br>  Now in the safe module there will be an open method replacing the standard open, and other methods can be wrapped in wrap.  This method can also be used as a decorator for eigenfunctions. <br><br>  Often, when you write service scripts, it turns out that a piece of one script needs to be used in another.  Therefore, it is better to immediately count on reusing them as modules, and at least to take out all the working actions in the method, and leave the service actions (for example, the processing of command line parameters) in the global code: <br><br><blockquote><ol><li>  <font color="#808080"><i>#! / usr / bin / python</i></font> </li><li>  <font color="#ff7700"><b>import</b></font> <font color="#dc143c">os</font> , <font color="#dc143c">shutil</font> , safe, <font color="#dc143c">sys</font> </li><li></li><li>  hosts_file = <font color="#483d8b">'/ etc / hosts'</font> </li><li></li><li>  @ safe.wrap ( <font color="#483d8b">'Error reading file {0}'</font> ) </li><li>  <font color="#ff7700"><b>def</b></font> writehost (ip, host): </li><li>  <font color="#ff7700"><b>with</b></font> safe.  <font color="#008000">open</font> (hosts_file, <font color="#483d8b">'a'</font> ) <font color="#ff7700"><b>as</b></font> f: </li><li>  f.write ( <font color="#483d8b">'.format (ip, host))</font> </li><li></li><li>  <font color="#483d8b">if __name__ == '</font> <font color="#dc143c">__main__</font> <font color="#483d8b">':</font> </li><li>  <font color="#483d8b">writehost (sys.argv [1:])</font> </li><li>  <font color="#483d8b">with safe.open (hosts_file, '</font> r <font color="#483d8b">') as f:</font> </li><li>  <font color="#483d8b">print f.read ()</font> </li></ol><br></blockquote><br><br>  Here, in fact, there is a possible exception that is not intercepted - this is reading the file (last line).  In order to process it with available means, we will have to put an action into the method, but, let's say, we don‚Äôt want to do it (a swarm of small methods is also not an option), and we will write a try-except construct.  In order not to repeat the already existing code that displays the message, we will move it into the safe module into a separate dump function: <br><br>  <em>(safe.py)</em> <br><blockquote><ol><li>  <font color="#ff7700"><b>def</b></font> catch (method, message, <font color="#dc143c">exceptions</font> , <font color="#66cc66">*</font> args, <font color="#66cc66">**</font> kwargs): </li><li>  <font color="#ff7700"><b>if</b></font> <font color="#ff7700"><b>not</b></font> <font color="#008000">isinstance</font> (message, <font color="#008000">str</font> ): </li><li>  <font color="#ff7700"><b>raise</b></font> <font color="#008000">TypeError</font> ( <font color="#483d8b">'Message text must be a string'</font> ) </li><li>  <font color="#ff7700"><b>try</b></font> : </li><li>  <font color="#ff7700"><b>return</b></font> method ( <font color="#66cc66">*</font> args) </li><li>  <font color="#ff7700"><b>except</b></font> <font color="#dc143c">exceptions</font> : </li><li>  quit (message, <font color="#66cc66">*</font> args) </li><li></li><li>  <font color="#ff7700"><b>def</b></font> wrap (method, message, <font color="#dc143c">exceptions</font> = ( <font color="#008000">IOError</font> , <font color="#008000">OSError</font> )): </li><li>  <font color="#ff7700"><b>def</b></font> fn ( <font color="#66cc66">*</font> args, <font color="#66cc66">**</font> kwargs): </li><li>  <font color="#ff7700"><b>return</b></font> catch (method, message, <font color="#dc143c">exceptions</font> , <font color="#66cc66">*</font> args, <font color="#66cc66">**</font> kwargs) </li><li>  <font color="#ff7700"><b>return</b></font> fn </li><li></li><li>  <font color="#008000">open</font> = wrap ( <font color="#008000">open</font> , <font color="#483d8b">'Can)</font> </li><li></li><li>  <font color="#483d8b">def quit (msg, * args):</font> </li><li>  <font color="#483d8b">sys.exit (msg.format (* args) + '</font> Error: <font color="#483d8b">', '</font> , <font color="#483d8b">' .join (map (str, sys.exc_info () [1] .args)), 1)</font> </li><li>  <font color="#483d8b"># not all arguments are strings, they need to be converted by str</font> </li></ol><br></blockquote><br><br>  <em>(main program)</em> <br><blockquote><ol><li>  ... </li><li>  <font color="#ff7700"><b>with</b></font> safe.  <font color="#008000">open</font> (hosts_file, <font color="#483d8b">'r'</font> ) <font color="#ff7700"><b>as</b></font> f: </li><li>  <font color="#ff7700"><b>try</b></font> : </li><li>  <font color="#ff7700"><b>print</b></font> <font color="#483d8b">''</font> .join (f) </li><li>  <font color="#ff7700"><b>except</b></font> <font color="#008000">IOError</font> : </li><li>  safe.quit ( <font color="#483d8b">'File {0} opened, but failed while reading.'</font> , hosts_file) </li><li>  ... </li></ol><br></blockquote><br>  <em>(Note: in my programs and in my safe module, I use decorators that check the data type.)</em> <br><br><h4>  What's next? </h4><br>  First, the exception trace contains a lot of useful information, much more than the one printed by Python.  It will be useful to make a method that saves this data somewhere in a file so that the user can send it to the developer. <br><br><h4>  Summary </h4><br>  Now for many typical cases, we have 4 ways to handle exceptions: <br>  take actions to a new method and decorate it with the wrap method <br>  decorate built-in methods with wrap too <br>  call any method through the catch exception handler <br>  write your try-except construct in the code and call the quit method in it <br><br>  ... and their labor costs are minimal: just write the name of the processor and the text of the error message.  Atypical exceptions will be quite rare, and for them we will write try-except, which does not complicate the code. </div><p>Source: <a href="https://habr.com/ru/post/74875/">https://habr.com/ru/post/74875/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../74866/index.html">The first reviews and crash tests HTC HD2</a></li>
<li><a href="../74868/index.html">First sexual experience</a></li>
<li><a href="../74872/index.html">Password recovery (mail.ru)</a></li>
<li><a href="../74873/index.html">How I made friends with memcache and propel in symfony</a></li>
<li><a href="../74874/index.html">Augmented Reality Magazine Cover</a></li>
<li><a href="../74876/index.html">Nokia began shipping the N900</a></li>
<li><a href="../74880/index.html">How I started the extra keys on the laptop</a></li>
<li><a href="../74881/index.html">Firefox 3.6 Beta 2</a></li>
<li><a href="../74882/index.html">Google Developer Day 2009 Report</a></li>
<li><a href="../74883/index.html">Extend Visual Studio functionality</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>