<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Unobvious problem of using assert</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Unit tests are an important part of any large enough project. I want to share with you a small detective story related to their unobvious massive fall...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>Unobvious problem of using assert</h1><div class="post__text post__text-html js-mediator-article">  Unit tests are an important part of any large enough project.  I want to share with you a small detective story related to their unobvious massive fall. <br><br>  It starts with the fact that in the project as a result of a certain innocuous commit, about 150 tests fell, while the set of falling tests was not stable.  The tests were not interconnected, the tests were performed sequentially.  The in-memory h2 database serves as a data source for tests.  The fall of the overwhelming majority of these 150 tests was accompanied by an error in the log: ‚ÄúCannot get a connection, pool timeout waiting for idle object‚Äù.  It should be noted that the connection pool size when running tests in a project is 1. <br><a name="habracut"></a><br>  A small lyrical digression: in the project code, the transaction is always interchanged from the flow, then the code is executed in a separate transaction, and finally, the transaction is back coupled.  For such cases, a helper class is written, the use of which looks like this: <br><br><pre><code class="java hljs">TransactionRunner.run(dbDataManager(), <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> MethodTransaction() { <span class="hljs-meta"><span class="hljs-meta">@Override</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> ExecutionResult </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">runInTransaction</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">()</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">throws</span></span></span><span class="hljs-function"> Exception </span></span>{ <span class="hljs-comment"><span class="hljs-comment">// ,       return result; } );</span></span></code> </pre> <br>  As a result of the analysis, it was revealed that the error begins to manifest itself after a failed test, which contains a call to the code in the transaction: 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
    <pre> <code class="java hljs">TransactionRunner.run(dbDataManager(), <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> MethodTransaction() { <span class="hljs-meta"><span class="hljs-meta">@Override</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> ExecutionResult </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">runInTransaction</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">()</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">throws</span></span></span><span class="hljs-function"> Exception </span></span>{ <span class="hljs-comment"><span class="hljs-comment">// ...   // assert   assert( 1, result.getSomeNotEqualOneIntValue() ); return result; } );</span></span></code> </pre> <br>  Let's look inside the TransactionRunner class, calling the method results in the following code: <br><br><pre> <code class="java hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">protected</span></span></span><span class="hljs-function"> ExecutionResult </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">run</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">()</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">throws</span></span></span><span class="hljs-function"> CommonException </span></span>{ Transaction outerTr = getThreadTransaction(); bindThreadTransaction(<span class="hljs-keyword"><span class="hljs-keyword">null</span></span>); <span class="hljs-keyword"><span class="hljs-keyword">try</span></span> { beginTransaction(); <span class="hljs-keyword"><span class="hljs-keyword">try</span></span> { setResult(transactionCode.runInTransaction()); } <span class="hljs-keyword"><span class="hljs-keyword">catch</span></span> (Exception e) { dbDataManager().rollbackTransaction(); <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (transaction.onException(<span class="hljs-keyword"><span class="hljs-keyword">this</span></span>, e)) <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> e; } dbDataManager().commitTransaction(); <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> getResult(); } <span class="hljs-keyword"><span class="hljs-keyword">catch</span></span> (Exception e) { <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> ExceptionUtil.createCommonException(e); } <span class="hljs-keyword"><span class="hljs-keyword">finally</span></span> { bindThreadTransaction(outerTr); } }</code> </pre> <br>  So what is the problem here?  And the problem is that the AssertionError resulting from the execution of the test code is not inherited from Exception, which means that the nested transaction is neither rolled back nor committed.  Since the size of the connection pool is one, we get that same error ‚ÄúCannot get a connection,‚Äù when trying to get a Connection object with subsequent tests. <br><br>  Moral: it is necessary to place assertions in tests with caution, and in the case of non-obvious and, in particular, massive drops, one of the solutions is to check whether objects that do not inherit from Exception take into account exception handling. <br><br>  The case seemed to me worthy of fixation, perhaps this experience will be useful to someone. </div><p>Source: <a href="https://habr.com/ru/post/420509/">https://habr.com/ru/post/420509/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../420499/index.html">Anatomy of recommendation systems. Part one</a></li>
<li><a href="../420501/index.html">Linux in RAM: debirf way 2018</a></li>
<li><a href="../420503/index.html">JS Developer Day, different cities and communities - one holiday</a></li>
<li><a href="../420505/index.html">Will OpenAI Five win the professional team at The International?</a></li>
<li><a href="../420507/index.html">Reference: global Internet for all and its creators</a></li>
<li><a href="../420511/index.html">Work as an IT specialist in the Far East - Amur Region</a></li>
<li><a href="../420513/index.html">Pirated copy of paid service in 39 lines of Python code</a></li>
<li><a href="../420515/index.html">Diarization based on GMM-UBM model and MAP adaptation algorithm</a></li>
<li><a href="../420517/index.html">Implementation of integer FFT on the FPGA</a></li>
<li><a href="../420519/index.html">Popularization of science</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>